version: '3.7'

services:
  dm_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
  dm_web:
    build: .
    command: python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dm_rest
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 8000:8000
    depends_on:
      - dm_db
volumes:
  postgres_data:

